// Scholarship data extracted from page  
// This will be moved to a separate data file later (Issue #42 - better organization)
export const scholarships = [
    {
        id: 'gates-cambridge',
        name: 'Gates Cambridge Scholarships',
        description: 'For international students; full funding',
        country: 'UK',
        countryCode: 'uk',
        level: 'Masters/PhD',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Oct 8/Dec 4 2025',
        deadlineCode: 'open',
        url: 'https://www.gatescambridge.org/apply'
    },
    {
        id: 'clarendon-oxford',
        name: 'Clarendon Fund Scholarships at Oxford',
        description: 'Full tuition + living costs',
        country: 'UK',
        countryCode: 'uk',
        level: 'Masters/PhD',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Jan 3/Jan 24 2026',
        deadlineCode: 'open',
        url: 'https://www.ox.ac.uk/admissions/graduate/fees-and-funding/fees-funding-and-scholarship-search/clarendon-fund'
    },
    {
        id: 'icsp-oregon',
        name: 'ICSP Scholarships at University of Oregon',
        description: 'Partial tuition',
        country: 'USA',
        countryCode: 'usa',
        level: 'Bachelors',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Jan 15/Feb 13 2026',
        deadlineCode: 'open',
        url: 'https://international.uoregon.edu/icsp'
    },
    {
        id: 'reach-oxford',
        name: 'Reach Oxford Scholarships',
        description: 'For developing countries; full funding',
        country: 'UK',
        countryCode: 'uk',
        level: 'Bachelors',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Oct 15 2025',
        deadlineCode: 'open',
        url: 'https://www.ox.ac.uk/admissions/undergraduate/fees-and-funding/oxford-support/reach-oxford-scholarships'
    },
    {
        id: 'ubc-scholars',
        name: 'International Scholars Program at UBC',
        description: 'Merit-based',
        country: 'Canada',
        countryCode: 'canada',
        level: 'Bachelors',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Nov 15/Dec 1 2025',
        deadlineCode: 'open',
        url: 'https://you.ubc.ca/financial-planning/scholarships-awards-international-students/'
    },
    {
        id: 'geneva-excellence',
        name: 'University of Geneva Excellence Masters Fellowships',
        description: 'Partial funding',
        country: 'Switzerland',
        countryCode: 'switzerland',
        level: 'Masters',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Feb 28 2026',
        deadlineCode: 'open',
        url: 'https://www.unige.ch/international/exchanges/masters-fellowship/'
    },
    {
        id: 'american-u-leader',
        name: 'American University Emerging Global Leader Scholarship',
        description: 'Full tuition for leaders',
        country: 'USA',
        countryCode: 'usa',
        level: 'Bachelors',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Jan 15 2026',
        deadlineCode: 'open',
        url: 'https://www.american.edu/provost/undergrad/emerging-global-leader/'
    },
    {
        id: 'east-west-center',
        name: 'East-West Center Graduate Degree Fellowship',
        description: 'Full support at UH',
        country: 'USA',
        countryCode: 'usa',
        level: 'Graduate',
        levelCode: 'graduate',
        field: 'Relevant to EWC goals',
        fieldCode: 'all',
        deadline: 'Dec 1 2025',
        deadlineCode: 'open',
        url: 'https://www.eastwestcenter.org/education/student-programs/graduate-degree-fellowship'
    },
    {
        id: 'mpower-monthly',
        name: 'MPOWER Monthly Scholarship (October)',
        description: '$1,000 awards',
        country: 'USA/Canada',
        countryCode: 'usa',
        level: 'All',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Oct 31 2025 (monthly)',
        deadlineCode: 'open',
        url: 'https://www.mpowerfinancing.com/scholarships/'
    },
    {
        id: 'sanima-nepal',
        name: 'Sanima Bank Scholarship for Plus Two',
        description: 'Local for Nepali students',
        country: 'Nepal',
        countryCode: 'nepal',
        level: 'Plus Two',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Oct 17 2025',
        deadlineCode: 'open',
        url: 'https://www.sanimabank.com/'
    },
    {
        id: 'knight-hennessy',
        name: 'Knight-Hennessy Scholars at Stanford',
        description: 'Full funding for graduate study',
        country: 'USA',
        countryCode: 'usa',
        level: 'Graduate',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Oct 9 2025',
        deadlineCode: 'open',
        url: 'https://knight-hennessy.stanford.edu/admission'
    },
    {
        id: 'peo-international',
        name: 'P.E.O. International Peace Scholarship',
        description: 'For women',
        country: 'USA',
        countryCode: 'usa',
        level: 'Graduate',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Dec 15 2025',
        deadlineCode: 'open',
        url: 'https://www.peointernational.org/about-peo-international-peace-scholarship-ips'
    },
    {
        id: 'fulbright-nepal',
        name: 'Fulbright Foreign Student Program (2026-27 cycle)',
        description: 'For Nepali citizens; full funding',
        country: 'USA',
        countryCode: 'usa',
        level: 'Masters/PhD',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'May 2026',
        deadlineCode: 'open',
        url: 'https://np.usembassy.gov/education-culture/educational-exchanges/fulbright-program/'
    },
    {
        id: 'humphrey-fellowship',
        name: 'Hubert H. Humphrey Fellowship',
        description: 'Mid-career',
        country: 'USA',
        countryCode: 'usa',
        level: 'Professional',
        levelCode: 'graduate',
        field: 'Various',
        fieldCode: 'all',
        deadline: 'Oct 1 2025',
        deadlineCode: 'open',
        url: 'https://www.humphreyfellowship.org/'
    },
    {
        id: 'aauw-intl',
        name: 'AAUW International Fellowships',
        description: 'For women',
        country: 'USA',
        countryCode: 'usa',
        level: 'Masters/PhD',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Nov 15 2025',
        deadlineCode: 'open',
        url: 'https://www.aauw.org/resources/programs/fellowships-grants/international-fellowships/'
    },
    {
        id: 'rotary-peace',
        name: 'Rotary Peace Fellowships',
        description: 'Full funding',
        country: 'Various',
        countryCode: 'other',
        level: 'Masters',
        levelCode: 'graduate',
        field: 'Peace studies',
        fieldCode: 'all',
        deadline: 'May 15 2026 (apps open Oct)',
        deadlineCode: 'open',
        url: 'https://www.rotary.org/en/our-programs/peace-fellowships'
    },
    {
        id: 'schwarzman',
        name: 'Schwarzman Scholars',
        description: 'Global affairs',
        country: 'China',
        countryCode: 'china',
        level: 'Masters',
        levelCode: 'graduate',
        field: 'Leadership',
        fieldCode: 'all',
        deadline: 'Oct 1 2025',
        deadlineCode: 'open',
        url: 'https://www.schwarzmanscholars.org/'
    },
    {
        id: 'erasmus-mundus',
        name: 'Erasmus Mundus Joint Masters',
        description: 'EU-funded; multiple programs',
        country: 'Europe',
        countryCode: 'europe',
        level: 'Masters',
        levelCode: 'graduate',
        field: 'Various',
        fieldCode: 'all',
        deadline: 'Oct 2025 - Feb 2026',
        deadlineCode: 'open',
        url: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en'
    },
    {
        id: 'commonwealth',
        name: 'Commonwealth Scholarships',
        description: 'For Commonwealth countries; full funding',
        country: 'UK',
        countryCode: 'uk',
        level: 'Masters/PhD',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Dec 17 2025',
        deadlineCode: 'open',
        url: 'https://cscuk.fcdo.gov.uk/scholarships/'
    },
    {
        id: 'vanier-canada',
        name: 'Vanier Canada Graduate Scholarships',
        description: 'Excellence',
        country: 'Canada',
        countryCode: 'canada',
        level: 'PhD',
        levelCode: 'phd',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Nov 1 2025',
        deadlineCode: 'open',
        url: 'https://vanier.gc.ca/'
    },
    {
        id: 'australia-awards',
        name: 'Australia Awards Scholarships',
        description: 'For Pacific/Asia',
        country: 'Australia',
        countryCode: 'australia',
        level: 'All',
        levelCode: 'undergraduate',
        field: 'Development',
        fieldCode: 'all',
        deadline: 'Feb 1 2026',
        deadlineCode: 'open',
        url: 'https://www.australiaawards.gov.au/'
    },
    {
        id: 'daad',
        name: 'DAAD Scholarships',
        description: 'Exchange',
        country: 'Germany',
        countryCode: 'germany',
        level: 'All',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Varies Oct-Dec 2025',
        deadlineCode: 'open',
        url: 'https://www.daad.de/en/'
    },
    {
        id: 'chevening',
        name: 'Chevening Scholarships',
        description: 'UK Government Leadership Scholarship',
        country: 'UK',
        countryCode: 'uk',
        level: 'Masters',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Nov 5 2025',
        deadlineCode: 'open',
        url: 'https://www.chevening.org/scholarships/'
    },
    {
        id: 'holland-scholarship',
        name: 'Holland Scholarship',
        description: 'Non-EEA students; €5,000',
        country: 'Netherlands',
        countryCode: 'netherlands',
        level: 'Bachelors/Masters',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'May 1 2026',
        deadlineCode: 'future',
        url: 'https://www.studyinholland.nl/finances/holland-scholarship'
    },
    {
        id: 'kgsp',
        name: 'Korean Government Scholarship (KGSP/GKS)',
        description: 'Full tuition + living expenses + language training',
        country: 'South Korea',
        countryCode: 'south-korea',
        level: 'Undergraduate/Graduate',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'March 31 2026',
        deadlineCode: 'open',
        url: 'https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do'
    },
    {
        id: 'eiffel-excellence',
        name: 'Eiffel Excellence Scholarship',
        description: 'Masters/PhD in engineering, sciences, economics',
        country: 'France',
        countryCode: 'france',
        level: 'Masters/PhD',
        levelCode: 'graduate',
        field: 'Engineering/Sciences',
        fieldCode: 'engineering',
        deadline: 'Jan 7 2026',
        deadlineCode: 'open',
        url: 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence'
    },
    {
        id: 'mext-japan',
        name: 'MEXT Scholarship (Japanese Government)',
        description: 'Full tuition + monthly stipend + airfare',
        country: 'Japan',
        countryCode: 'japan',
        level: 'Undergraduate/Graduate',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'April-June 2026',
        deadlineCode: 'open',
        url: 'https://www.studyinjapan.go.jp/en/planning/scholarship/'
    },
    {
        id: 'swedish-institute',
        name: 'Swedish Institute Scholarships',
        description: 'For developing countries; full tuition + living expenses',
        country: 'Sweden',
        countryCode: 'sweden',
        level: 'Masters',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Feb 18 2026',
        deadlineCode: 'open',
        url: 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/'
    },
    {
        id: 'nz-scholarships',
        name: 'New Zealand Scholarships',
        description: 'For developing countries; full funding',
        country: 'New Zealand',
        countryCode: 'new-zealand',
        level: 'Undergraduate/Masters/PhD',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'March 31 2026',
        deadlineCode: 'open',
        url: 'https://www.nzscholarships.govt.nz/'
    },
    {
        id: 'turkiye',
        name: 'Türkiye Scholarships',
        description: 'Turkish Government; full funding',
        country: 'Turkey',
        countryCode: 'turkey',
        level: 'Undergraduate/Graduate/PhD',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Feb 20 2026',
        deadlineCode: 'open',
        url: 'https://www.turkiyeburslari.gov.tr/'
    },
    {
        id: 'italy-govt',
        name: 'Italian Government Scholarships',
        description: 'For international students',
        country: 'Italy',
        countryCode: 'italy',
        level: 'Undergraduate/Masters/PhD',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'April-May 2026',
        deadlineCode: 'open',
        url: 'https://studyinitaly.esteri.it/en/scholarships'
    },
    {
        id: 'csc-china',
        name: 'Chinese Government Scholarship (CSC)',
        description: 'Full tuition + stipend + accommodation',
        country: 'China',
        countryCode: 'china',
        level: 'Undergraduate/Masters/PhD',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Jan 15 - Apr 30 2026',
        deadlineCode: 'open',
        url: 'https://www.campuschina.org/'
    },
    {
        id: 'yale-yygs',
        name: 'Yale Young Global Scholars',
        description: 'Need-based financial aid available',
        country: 'USA',
        countryCode: 'usa',
        level: 'High School',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Ongoing 2025-2026',
        deadlineCode: 'open',
        url: 'https://globalscholars.yale.edu/'
    },
    {
        id: 'clark-global',
        name: 'Clark Global Scholars Program',
        description: 'Full tuition + $2,500/year; at Clark University',
        country: 'USA',
        countryCode: 'usa',
        level: 'Bachelors',
        levelCode: 'undergraduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Nov 1 2025/Jan 15 2026',
        deadlineCode: 'open',
        url: 'https://www.clarku.edu/offices/admissions/global-scholars-program/'
    },
    {
        id: 'pearson-toronto',
        name: 'Lester B. Pearson International Scholarship',
        description: 'University of Toronto; full tuition + books + incidentals',
        country: 'Canada',
        countryCode: 'canada',
        level: 'Bachelors',
        levelCode: 'graduate',
        field: 'All',
        fieldCode: 'all',
        deadline: 'Nov 2025',
        deadlineCode: 'open',
        url: 'https://future.utoronto.ca/pearson/'
    }
];
