// Civora — Scholarship Database
// Updated: July 2026 | 2026-2027 application cycle
// All deadlines are for the upcoming cycle. Dates marked as approximate (~) when official dates haven't been announced yet.

export const scholarships = [
  {
    id: 'fulbright-nepal',
    name: 'Fulbright Foreign Student Program',
    country: 'USA',
    countryCode: 'usa',
    countryFlag: '🇺🇸',
    organizer: 'U.S. Department of State',
    level: ['Masters', 'PhD'],
    levelCode: 'graduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Living costs', 'Airfare', 'Health insurance', 'Book allowance'],
    deadline: 'April 2027 (Nepal cycle)',
    deadlineDate: '2027-04-15',
    eligibility: [
      'Nepali citizen with bachelor\'s degree',
      'Minimum 3 years work experience preferred',
      'Strong English proficiency (TOEFL/IELTS)'
    ],
    url: 'https://np.usembassy.gov/education-culture/educational-exchanges/fulbright-program/',
    description: 'The Fulbright Program provides full funding for Nepali students to pursue graduate studies at U.S. universities. One of the most prestigious scholarships available.'
  },
  {
    id: 'chevening',
    name: 'Chevening Scholarships',
    country: 'UK',
    countryCode: 'uk',
    countryFlag: '🇬🇧',
    organizer: 'UK Government (FCDO)',
    level: ['Masters'],
    levelCode: 'graduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Living allowance', 'Return airfare', 'Thesis grant'],
    deadline: '~November 5, 2026',
    deadlineDate: '2026-11-05',
    eligibility: [
      'At least 2 years work experience',
      'Return to home country for 2 years after',
      'Apply to 3 eligible UK university courses'
    ],
    url: 'https://www.chevening.org/scholarships/',
    description: 'UK Government\'s global scholarship programme for future leaders. Covers a one-year Master\'s degree at any UK university.'
  },
  {
    id: 'daad',
    name: 'DAAD Scholarships',
    country: 'Germany',
    countryCode: 'germany',
    countryFlag: '🇩🇪',
    organizer: 'German Academic Exchange Service',
    level: ['Masters', 'PhD'],
    levelCode: 'graduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Monthly stipend (€934-1,300)', 'Health insurance', 'Travel allowance', 'Study allowance'],
    deadline: 'Varies by program, Oct–Dec 2026',
    deadlineDate: '2026-10-15',
    eligibility: [
      'Bachelor\'s degree completed within last 6 years',
      'Strong academic record',
      'English or German proficiency depending on program'
    ],
    url: 'https://www.daad.de/en/',
    description: 'Germany\'s largest scholarship organization offering hundreds of programs across all disciplines at German universities.'
  },
  {
    id: 'mext-japan',
    name: 'MEXT Scholarship',
    country: 'Japan',
    countryCode: 'japan',
    countryFlag: '🇯🇵',
    organizer: 'Japanese Government (MEXT)',
    level: ['Bachelors', 'Masters', 'PhD'],
    levelCode: 'undergraduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Monthly stipend (¥117,000-¥148,000)', 'Round-trip airfare', 'Japanese language training'],
    deadline: 'April–June 2027 (Embassy track)',
    deadlineDate: '2027-04-01',
    eligibility: [
      'Nepali citizen under 35 years old',
      'Good academic standing',
      'Willing to learn Japanese language'
    ],
    url: 'https://www.studyinjapan.go.jp/en/planning/scholarship/',
    description: 'One of the most comprehensive scholarships available — includes free Japanese language training before your degree program begins.'
  },
  {
    id: 'kgsp',
    name: 'Global Korea Scholarship (GKS)',
    country: 'South Korea',
    countryCode: 'south-korea',
    countryFlag: '🇰🇷',
    organizer: 'Korean Government (NIIED)',
    level: ['Bachelors', 'Masters', 'PhD'],
    levelCode: 'undergraduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Monthly stipend', 'Round-trip airfare', 'Korean language training', 'Settlement allowance'],
    deadline: '~February–March 2027',
    deadlineDate: '2027-02-28',
    eligibility: [
      'Nepali citizen with GPA 80% or above',
      'Under 25 (Bachelor\'s) or under 40 (Graduate)',
      'No Korean ancestry required'
    ],
    url: 'https://www.studyinkorea.go.kr/en/sub/gks/allnew_invite.do',
    description: 'South Korea\'s flagship scholarship includes 1 year of Korean language training before your degree program. One of the most generous packages available.'
  },
  {
    id: 'csc-china',
    name: 'Chinese Government Scholarship (CSC)',
    country: 'China',
    countryCode: 'china',
    countryFlag: '🇨🇳',
    organizer: 'China Scholarship Council',
    level: ['Bachelors', 'Masters', 'PhD'],
    levelCode: 'undergraduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Accommodation', 'Monthly stipend', 'Medical insurance'],
    deadline: 'January–April 2027',
    deadlineDate: '2027-01-15',
    eligibility: [
      'Non-Chinese citizen in good health',
      'Bachelor\'s for Master\'s, Master\'s for PhD',
      'Age limits vary by program level'
    ],
    url: 'https://www.campuschina.org/',
    description: 'China\'s national scholarship covering study at over 280 Chinese universities. Multiple application channels available through embassy or direct university application.'
  },
  {
    id: 'turkiye',
    name: 'Türkiye Bursları (Turkey Scholarships)',
    country: 'Turkey',
    countryCode: 'turkey',
    countryFlag: '🇹🇷',
    organizer: 'Republic of Türkiye',
    level: ['Bachelors', 'Masters', 'PhD'],
    levelCode: 'undergraduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Monthly stipend', 'Accommodation', 'Health insurance', 'Turkish language course', 'Flight ticket'],
    deadline: '~February 20, 2027',
    deadlineDate: '2027-02-20',
    eligibility: [
      'Under 21 (Bachelor\'s), 30 (Master\'s), 35 (PhD)',
      'Minimum 70% GPA (Bachelor\'s) or 75% (Graduate)',
      'No Turkish citizenship'
    ],
    url: 'https://www.turkiyeburslari.gov.tr/',
    description: 'One of the most comprehensive scholarship programs in the world — covers everything including 1 year of Turkish language training.'
  },
  {
    id: 'australia-awards',
    name: 'Australia Awards Scholarships',
    country: 'Australia',
    countryCode: 'australia',
    countryFlag: '🇦🇺',
    organizer: 'Australian Government (DFAT)',
    level: ['Masters', 'PhD'],
    levelCode: 'graduate',
    field: 'Development-related fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Return airfare', 'Living allowance', 'Health insurance', 'Pre-course English support'],
    deadline: '~April 30, 2027',
    deadlineDate: '2027-04-30',
    eligibility: [
      'Nepali citizen (eligible developing country)',
      'Minimum 2 years work experience',
      'IELTS 6.5 overall (no band below 6.0)'
    ],
    url: 'https://www.australiaawards.gov.au/',
    description: 'Australian Government scholarships focusing on development outcomes. Scholars are expected to contribute to Nepal\'s development upon return.'
  },
  {
    id: 'erasmus-mundus',
    name: 'Erasmus Mundus Joint Master Degrees',
    country: 'Europe (Multiple)',
    countryCode: 'europe',
    countryFlag: '🇪🇺',
    organizer: 'European Commission',
    level: ['Masters'],
    levelCode: 'graduate',
    field: 'Various specialized programs',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Monthly allowance (€1,400)', 'Travel costs', 'Installation costs', 'Insurance'],
    deadline: 'Varies by program, Oct 2026–Feb 2027',
    deadlineDate: '2026-10-01',
    eligibility: [
      'Bachelor\'s degree in relevant field',
      'Strong academic record',
      'English proficiency (varies by program)'
    ],
    url: 'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
    description: 'Study in 2-3 European countries during your Master\'s degree. Over 100 joint programs available across all disciplines.'
  },
  {
    id: 'adb-japan',
    name: 'ADB-Japan Scholarship Program',
    country: 'Various (ADB member countries)',
    countryCode: 'japan',
    countryFlag: '🇯🇵',
    organizer: 'Asian Development Bank & Japan',
    level: ['Masters'],
    levelCode: 'graduate',
    field: 'Development-related (Economics, Business, Science, Engineering)',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Monthly subsistence', 'Housing allowance', 'Book allowance', 'Medical insurance', 'Travel'],
    deadline: '~December 2026 (varies by institution)',
    deadlineDate: '2026-12-01',
    eligibility: [
      'Citizen of ADB borrowing member country (Nepal eligible)',
      'Bachelor\'s degree + 2 years work experience',
      'Admitted to a participating academic institution'
    ],
    url: 'https://www.adb.org/what-we-do/adb-japan-scholarship-program',
    description: 'For development professionals from ADB member countries to study at top institutions across Asia-Pacific. Strong focus on development impact.'
  },
  {
    id: 'aauw-intl',
    name: 'AAUW International Fellowships',
    country: 'USA',
    countryCode: 'usa',
    countryFlag: '🇺🇸',
    organizer: 'American Association of University Women',
    level: ['Masters', 'PhD', 'Postdoc'],
    levelCode: 'graduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'partial',
    covers: ['$20,000–$50,000 fellowship grant'],
    deadline: '~November 15, 2026',
    deadlineDate: '2026-11-15',
    eligibility: [
      'Women only — non-U.S. citizens',
      'Must hold equivalent of U.S. bachelor\'s degree',
      'Plan to return to home country after studies'
    ],
    url: 'https://www.aauw.org/resources/programs/fellowships-grants/international-fellowships/',
    description: 'For women pursuing full-time graduate or postdoctoral study in the U.S. who plan to return to their home countries to advance careers.'
  },
  {
    id: 'commonwealth',
    name: 'Commonwealth Scholarships',
    country: 'UK',
    countryCode: 'uk',
    countryFlag: '🇬🇧',
    organizer: 'Commonwealth Scholarship Commission',
    level: ['Masters', 'PhD'],
    levelCode: 'graduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Living allowance', 'Return airfare', 'Thesis grant', 'Warm clothing allowance'],
    deadline: '~December 2026',
    deadlineDate: '2026-12-17',
    eligibility: [
      'Citizen of Commonwealth country (Nepal is eligible)',
      'Hold first degree of upper second class (2:1)',
      'Unable to afford study in UK without scholarship'
    ],
    url: 'https://cscuk.fcdo.gov.uk/scholarships/',
    description: 'UK government-funded scholarships for talented individuals from Commonwealth countries who could not otherwise study in the UK.'
  },
  {
    id: 'nz-scholarships',
    name: 'New Zealand Scholarships',
    country: 'New Zealand',
    countryCode: 'new-zealand',
    countryFlag: '🇳🇿',
    organizer: 'New Zealand Government (MFAT)',
    level: ['Masters', 'PhD'],
    levelCode: 'graduate',
    field: 'Development-related fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Living allowance', 'Return airfare', 'Health insurance', 'Establishment allowance'],
    deadline: '~March 2027',
    deadlineDate: '2027-03-31',
    eligibility: [
      'Citizen of eligible developing country (Nepal eligible)',
      'Meet English language requirements',
      'Not a permanent resident of New Zealand'
    ],
    url: 'https://www.nzscholarships.govt.nz/',
    description: 'New Zealand Government scholarships supporting individuals from developing countries to gain skills that contribute to their home country\'s development.'
  },
  {
    id: 'stipendium-hungaricum',
    name: 'Stipendium Hungaricum',
    country: 'Hungary',
    countryCode: 'hungary',
    countryFlag: '🇭🇺',
    organizer: 'Hungarian Government',
    level: ['Bachelors', 'Masters', 'PhD'],
    levelCode: 'undergraduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Monthly stipend (HUF 43,700–140,000)', 'Accommodation', 'Medical insurance'],
    deadline: '~January 15, 2027',
    deadlineDate: '2027-01-15',
    eligibility: [
      'Citizen of partner country (Nepal has bilateral agreement)',
      'No Hungarian citizenship',
      'Meet academic requirements of chosen program'
    ],
    url: 'https://stipendiumhungaricum.hu/',
    description: 'Hungary\'s government scholarship program with over 600 study programs available. Growing number of English-taught programs across all fields.'
  },
  {
    id: 'gates-cambridge',
    name: 'Gates Cambridge Scholarships',
    country: 'UK',
    countryCode: 'uk',
    countryFlag: '🇬🇧',
    organizer: 'Gates Cambridge Trust',
    level: ['Masters', 'PhD'],
    levelCode: 'graduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Maintenance allowance', 'Return airfare', 'Academic development funding'],
    deadline: '~October 2026 / December 2026',
    deadlineDate: '2026-10-08',
    eligibility: [
      'Outstanding academic record',
      'Non-UK citizen applying to University of Cambridge',
      'Commitment to improving the lives of others'
    ],
    url: 'https://www.gatescambridge.org/apply',
    description: 'One of the most prestigious international scholarships — for outstanding applicants from outside the UK to pursue graduate study at Cambridge.'
  },
  {
    id: 'knight-hennessy',
    name: 'Knight-Hennessy Scholars (Stanford)',
    country: 'USA',
    countryCode: 'usa',
    countryFlag: '🇺🇸',
    organizer: 'Stanford University',
    level: ['Masters', 'PhD', 'Professional'],
    levelCode: 'graduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Stipend', 'Housing allowance', 'Travel', 'Leadership programming'],
    deadline: '~October 2026',
    deadlineDate: '2026-10-09',
    eligibility: [
      'Bachelor\'s degree from any country',
      'Apply simultaneously to Stanford graduate program',
      'Demonstrated leadership and civic commitment'
    ],
    url: 'https://knight-hennessy.stanford.edu/admission',
    description: 'Stanford\'s premier fellowship for graduate students demonstrating independence of thought, purposeful leadership, and civic mindset.'
  },
  {
    id: 'swedish-institute',
    name: 'Swedish Institute Scholarships (SISGP)',
    country: 'Sweden',
    countryCode: 'sweden',
    countryFlag: '🇸🇪',
    organizer: 'Swedish Institute',
    level: ['Masters'],
    levelCode: 'graduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Living allowance (SEK 10,000/month)', 'Travel grant', 'Insurance'],
    deadline: '~February 2027',
    deadlineDate: '2027-02-18',
    eligibility: [
      'Citizen of eligible developing country (Nepal eligible)',
      'Minimum 3,000 hours work/volunteer experience',
      'Demonstrated leadership experience'
    ],
    url: 'https://si.se/en/apply/scholarships/swedish-institute-scholarships-for-global-professionals/',
    description: 'For future global leaders from developing countries. Strong emphasis on professional experience and leadership potential.'
  },
  {
    id: 'eiffel-excellence',
    name: 'Eiffel Excellence Scholarship',
    country: 'France',
    countryCode: 'france',
    countryFlag: '🇫🇷',
    organizer: 'French Ministry of Europe & Foreign Affairs',
    level: ['Masters', 'PhD'],
    levelCode: 'graduate',
    field: 'Engineering, Sciences, Economics, Law, Political Science',
    fieldCode: 'engineering',
    fundingType: 'fully-funded',
    covers: ['Monthly allowance (€1,181)', 'Return airfare', 'Health insurance', 'Housing assistance', 'Cultural activities'],
    deadline: '~January 2027',
    deadlineDate: '2027-01-07',
    eligibility: [
      'Non-French citizen, max age 25 (Masters) or 30 (PhD)',
      'Not already residing in France',
      'Applied through a French higher education institution'
    ],
    url: 'https://www.campusfrance.org/en/eiffel-scholarship-program-of-excellence',
    description: 'France\'s prestigious scholarship targeting excellence in science, engineering, economics, and law. Candidates are nominated by French institutions.'
  },
  {
    id: 'schwarzman',
    name: 'Schwarzman Scholars',
    country: 'China',
    countryCode: 'china',
    countryFlag: '🇨🇳',
    organizer: 'Schwarzman Scholars / Tsinghua University',
    level: ['Masters'],
    levelCode: 'graduate',
    field: 'Public Policy, Economics, Business, International Studies',
    fieldCode: 'business',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Room and board', 'Travel', 'Health insurance', 'Study trips'],
    deadline: '~September 2026',
    deadlineDate: '2026-09-15',
    eligibility: [
      'Bachelor\'s degree (completed before enrollment)',
      'Age 18-28 at time of enrollment',
      'English proficiency required'
    ],
    url: 'https://www.schwarzmanscholars.org/',
    description: 'A one-year Master\'s program at Tsinghua University in Beijing — designed to prepare future leaders to the geopolitical landscape of the 21st century.'
  },
  {
    id: 'rotary-peace',
    name: 'Rotary Peace Fellowships',
    country: 'Various',
    countryCode: 'other',
    countryFlag: '🌍',
    organizer: 'Rotary Foundation',
    level: ['Masters', 'Certificate'],
    levelCode: 'graduate',
    field: 'Peace & Conflict Resolution',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['Tuition', 'Room and board', 'Travel', 'Internship expenses'],
    deadline: '~May 15, 2027',
    deadlineDate: '2027-05-15',
    eligibility: [
      'Strong commitment to peace and conflict resolution',
      'Minimum 3 years relevant work experience',
      'Proficiency in English + second language preferred'
    ],
    url: 'https://www.rotary.org/en/our-programs/peace-fellowships',
    description: 'Study at one of Rotary\'s Peace Centers at leading universities worldwide. For professionals dedicated to peace, conflict resolution, and development.'
  },
  {
    id: 'vanier-canada',
    name: 'Vanier Canada Graduate Scholarships',
    country: 'Canada',
    countryCode: 'canada',
    countryFlag: '🇨🇦',
    organizer: 'Government of Canada',
    level: ['PhD'],
    levelCode: 'phd',
    field: 'Health, Sciences, Engineering, Social Sciences, Humanities',
    fieldCode: 'all',
    fundingType: 'fully-funded',
    covers: ['$50,000 CAD per year for 3 years'],
    deadline: '~November 2026',
    deadlineDate: '2026-11-01',
    eligibility: [
      'Nominated by a Canadian university',
      'Pursuing first doctoral degree',
      'Demonstrated leadership skills and research potential'
    ],
    url: 'https://vanier.gc.ca/',
    description: 'Canada\'s most prestigious doctoral scholarship — $50,000/year for 3 years. Open to both Canadian and international students.'
  },
  {
    id: 'holland-scholarship',
    name: 'Holland Scholarship',
    country: 'Netherlands',
    countryCode: 'netherlands',
    countryFlag: '🇳🇱',
    organizer: 'Dutch Ministry of Education',
    level: ['Bachelors', 'Masters'],
    levelCode: 'undergraduate',
    field: 'All Fields',
    fieldCode: 'all',
    fundingType: 'partial',
    covers: ['€5,000 one-time grant'],
    deadline: '~May 1, 2027',
    deadlineDate: '2027-05-01',
    eligibility: [
      'Non-EEA nationality (Nepal eligible)',
      'First time studying in the Netherlands',
      'Admitted to a participating Dutch university'
    ],
    url: 'https://www.studyinholland.nl/finances/holland-scholarship',
    description: 'A €5,000 grant for non-EEA students starting their first year of study at a participating Dutch university. Combine with other funding for full coverage.'
  }
];
